### ISSUE TITLE
Make handleMessage accept a boolean to determine if all chat is logged to the console.

### ISSUE THREAD

**Issue by jwshive** [jamesqquick/Quick-Chat-Bot#4]
I'm speaking specifically about the DiscordMessageHandler because that's what I'm presently using.

I run the bot non-interactively and I don't want it to still messages i'll never see to the console. I'd only worry about errors. I'd like to see
` console.info(`${msg.author.username}: ${msg.content}`);`
Wrapped in some sort of a if (showInfo === true) or switch statement to turn the console logging on or off.

Ideally handled in the initialization

const bot = new QuickDiscordBot({
  botToken: bot_token,
  commandsDir: path.join(__dirname, "commands"),
  ignoreChannels: [],
  testMode: testMode,
  testChannel: "secret-bot-testing",
  ignoreBots: true,
  showChat: false,   // <---
});

**Comment by jamesqquick** [comment]
This is a great idea. Any chance you'd like to take a stab at a PR @jwshive ?

**Comment by jwshive** [comment]
I'm pretty new to JS and have never generated a pull request, but I'll give it a shot.

**Comment by jamesqquick** [comment]
That would be awesome. Happy to answer questions if you have any. Also, I run a Discord server if you're interested in joining and asking questions there.

**Comment by jamesqquick** [comment]
Feature added by @jwshive Nice job!!
